### ISSUE TITLE
consulta de asignación de  categorías

### ISSUE THREAD

**Issue by cesarriat** [puigalex/AMP-Tech#1]
hola antes q nada felicitarte, soy un fiel seguidor de tu canal, paso a consultarte en el archivo predict se escribe ` if answer == 0:` y a eso se le asigna gato, gorila, duda es en q parte del codigo se asigna eso osea como se q el 0 corresponde ala carpeta q contiene las fotos de gatos o gorila o viceversa
saludos desde argentina

**Comment by Javiersuing** [comment]
Hola Alex misma, pregunta, te lo digo porque no le esta atinando a las imágenes que le cargo desde internet y al probar con imágenes de gato de entrenamiento como de prueba, las predice como perro.

**Comment by Javiersuing** [comment]
Hola cesarriat, logre avanzar con la VGG16 (vídeo posterior), la cual después de un par de ajustes, logre una precisión del 96%, con dicha precisión valide las categorías, tanto con datos de entrenamiento, como con datos nuevos. Mi conclusión es que las categorías quedan por orden alfabético, tal como se ven por defecto dentro de las carpetas de entrenamiento y validación, es decir 0, 1, 2 corresponden a gato, gorila y perro respectivamente, (si las tuvieras en ingles serían ape, cat, dog).

**Comment by cesarriat** [comment]
Mil gracias te consulto por ahi sabes de un tutorial q sea a real time de
object detection con google colab? Es decir poder usar la web cam

**Comment by Javiersuing** [comment]
Hola, sugiero cierres este issue e inicies uno nuevo donde se pueda abordar ese otro tema. Te comparto un link donde vi un código sencillo para usar la web cam y que seguro lo podrás ejecutar desde colab, (aunque no veo necesidad) https://www.youtube.com/watch?v=WIbYP5rhcUc
