### ISSUE TITLE
error en lectura de imagenes

### ISSUE THREAD

**Issue by SERIBO92** [puigalex/AMP-Tech#2]
Hola Alex, estoy empezando con python y las CNN, cuando termine con el código, me sale un error que dice:

 File "C:\Users\57300\.conda\envs\Ambiente\lib\site-packages\keras_preprocessing\image\utils.py", line 108, in load_img
    raise ImportError('Could not import PIL.Image. '

ImportError: Could not import PIL.Image. The use of `load_img` requires PIL.

La verdad no he encontrado aún por qué se esta presentando, sin embargo me sale el mismo error con tu código.

Por otro lado, como puedo configurar para que el código se ejecute mediante la GTX?

**Comment by Javiersuing** [comment]
Hola Seribo92, a mi me salió el mismo error en el archivo de predicción y lo corregí instalando la librería, como PIL ya esta obsoleto debes instalar Pillow así:
**pip install Pillow**
Si no te funciona coloca el error en google y encontrarás soluciones en stackoverflow.

Por cierto después de eso me salió otro error: Unknown initializer: GlorotUniform
Ese lo corriges cambiando esto:
from keras.models import load_model
por esto:
from tensorflow.keras.models import load_model

Saludos

**Comment by SERIBO92** [comment]
Muchas gracias @Javiersuing excelente tu ayuda, tambien me salio el mismo error y con tu sugerencia se solucionó de inmediato.

**Comment by Javiersuing** [comment]
Que bien! SERIBO92, en ese caso podrías cerrar este issue, el cual veo sigue abierto y supongo eres el único que puede cerrarlo. Saludos.
